version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  version: 2
  orbs_pipeline:
    jobs:
      - orb-tools/lint
          filters: &filters-development
            branches:
              only:
                - develop
      - orb-tools/pack
          filters:
            <<: *filters-development
      - hold-for-dev-publish:
          type: approval
          requires:
            - orb-tools/lint
            - orb-tools/pack
          filters:
            <<: *filters-development
      - orb-tools/publish-dev:
          orb-name: dm-circleci-orbs/devops-k8s
          requires:
            - hold-for-dev-publish
          filters:
            <<: *filters-development
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: dm-circleci-orbs/devops-k8s
          add-pr-comment: true
          fail-if-semver-not-indicated: true
          publish-version-tag: true
          filters:
            branches:
              only:
                - master