version: 2.1

orbs:
  orb-tools: circleci/orb-tools@10.0

workflows:
  version: 2
  orbs_pipeline:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: dm-circleci-orbs/devops-k8s
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: dm-circleci-orbs/devops-k8s
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only:
                - master
